//
// lambda library v1.0
// Copyright (c) 2011, Alvaro J. Gutierrez
//
var lambda=function(){function a(a){switch(typeof a){case "string":return o(A(a),[],"'"+a.replace("'","\\'")+"'");case "function":return a.lambda?a:o(a,[],a.name||"function");default:throw TypeError("Invalid function for lambda");}}function o(a,b,c){var g=d(Math.max(a.length-(b.length-k(b,l)),0),function(){var h;h=i.call(arguments);for(var g=l,f=i.call(b),m=0,d=0;m<b.length;++m)if(g(b[m]))for(;d<h.length;++d)if(!g(h[d])){f[m]=h[d];break}h=f.concat(i.call(h,d));return Math.max(a.length-(h.length-k(h,
l)),0)?o(a,h,c):a.apply(this,h)});g.lambda=!0;g.toString=p(B,b,c);return g}function B(a,b){return"lambda("+b+")"+j(a,function(a){return"("+(l(a)?"_":a)+")"}).join("")}function l(a){return a===q._||a===void 0}function d(a,b){if(a<0)throw Error();var c=j(Array(a),function(a,b){return"$"+b});return c=Function.bind?Function.apply(null,c.concat(["return this.apply(null, arguments)"])).bind(b):eval("function("+c.join(", ")+") { return fn.apply(null, arguments) }")}function r(e,b){var c={},g=b||String;return d(e.length,
function(){var b=i.call(arguments),d=g(b),d=c[d]||(c[d]=[]),f=s(d,function(e){return e[0].length===b.length&&t(u(e[0],b),a.identical)});return(f?f:d[d.length]=[b,e.apply(this,b)])[1]})}function v(a){return function(b,c){return a.call(this,c,b)}}function w(){return x(arguments,function(a,b){return d(b.length,function(){return a.call(this,b.apply(this,arguments))})})}function p(a){var b=i.call(arguments,1);return d(Math.max(0,a.length-b.length),function(){return a.apply(this,b.concat(i.call(arguments)))})}
function f(a,b){for(var c=0;c<a.length;++c){var g=b.call(this,a[c],c);if(g!==void 0)return g}}function y(a,b){return f(a,function(a,e){if(b.call(this,a,e))return!0})||!1}function t(a,b){return!f(a,function(a,e){if(!b.call(this,a,e))return!0})}function s(a,b){return f(a,function(a,e){if(b.call(this,a,e))return a})}function k(a,b){var c=0;f(a,function(a,e){b.call(this,a,e)&&++c});return c}function j(a,b){var c=[];f(a,function(a,e){c.push(b.call(this,a,e))});return c}function x(a,b,c){c===void 0&&(c=
a[0],a=i.call(a,1));f(a,function(a){c=b.call(this,c,a)});return c}function z(a,b){return a.apply(this,b)}function n(a,b){return j(a,function(a){return a[b]})}function u(){var a=i.call(arguments),b=Array(Math.max.apply(null,n(a,"length")));f(b,function(c,d){b[d]=n(a,d)});return b}var q=this,i=Array.prototype.slice;if(q._==void 0)q._=void 0;var C=/\b_(\d+)?\b/g,A=r(function(a){var b=0,a="return "+a.replace(C,function(a,c){return c?(c=Math.max(1,parseInt(c)),b=Math.max(b,c),"$"+(c-1)):"$"+b++}),c=j(Array(b),
function(a,b){return"$"+b});return Function.apply(null,c.concat([a]))});a.id=a.identity=a(function(a){return a});a.noop=a(function(){});a.bind=a(function(a,b){return d(a.length,function(){return a.apply(b,arguments)})});a.flip=a(v);a.memoize=a(r);a.curry=a(p);a.compose=a(w);a.apply=a(z);a.not=a("!_");a.and=a("_ && _");a.or=a("_ || _");a.xor=a("(_1 || _2) && !(_1 && _2)");a.inc=a.increment=a("++_");a.dec=a.decrement=a("--_");a.bitNot=a("~_");a.bitOr=a("_ | _");a.bitAnd=a("_ & _");a.bitXor=a("_ ^ _");
a.add=a.plus=a("_ + _");a.sub=a.minus=a("_ - _");a.mul=a.times=a("_ * _");a.div=a.over=a("_ / _");a.mod=a.remain=a("_ % _");a.lshift=a.leftShift=a("_ << _");a.rshift=a.rightShift=a("_ >> _");a.zshift=a.logicShift=a("_ >>> _");a.eq=a.equals=a("_ == _");a.ne=a.unequals=a("_ != _");a.gt=a.greater=a("_ > _");a.lt=a.lesser=a("_ < _");a.ge=a.greaterEqual=a("_ >= _");a.le=a.lesserEqual=a("_ <= _");a.identical=a("_ === _");a.unidentical=a("_ !== _");a.power=a(Math.pow);a.square=a.power(_,2);a.cube=a.power(_,
3);a.even=a("_ % 2 == 0");a.odd=a(w(a.not,a.even));a.get=a("_[_]");a.set=a("_[_] = _");a.has=a("_.hasOwnProperty(_)");a.del=a("delete _");a.type=a("typeof _");a.is=a("_ instanceof _");a.cons=a("_.constructor");a.prot=a("_.prototype");a.fanout=a(function(){var a=i.call(arguments),b=Math.max.apply(null,n(a,"length"));return d(b,function(){return j(a,p(v(z),arguments))})});a.ifElse=a("_ ? _ : _");a.concat=a("_.concat(_)");a.indexOf=a("_.indexOf(_)");a.join=a("_.join(_)");a.pop=a("_.pop()");a.push=a("_.push(_)");
a.reverse=a("_.reverse()");a.shift=a("_.shift()");a.slice=a("_.slice(_, _)");a.sort=a("_.sort(_)");a.splice=a("_.splice(_, _)");a.unshift=a("_.unshift(_)");a.valueOf=a("_.valueOf()");a.each=a(f);a.count=a(k);a.map=a(j);a.pluck=a(n);a.zip=a(u);a.fold=a(x);a.all=a(t);a.any=a(y);a.none=a(function(a,b){return!y(a,b)});a.one=a(function(a,b){return k(a,b)===1});a.find=a(s);a.first=a.get(_,0);a.second=a.get(_,1);a.third=a.get(_,2);a.last=a("_1[_1.length - 1]");a.lead=a("_.slice(0, -1)");a.tail=a("_.slice(1)");
a.take=a("_.slice(0, _)");a.drop=a("_.slice(_)");a.part=a.fanout(a.take,a.drop);a.nil=a.empty=a("_.length == 0");a.len=a("_.length");a.str=a.toString=a("_.toString()");return a}();
